//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace currency.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://server/", ConfigurationName="ServiceReference1.CurrencyConverter")]
    public interface CurrencyConverter {
        
        // CODEGEN: Generating message contract since element name return from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://server/CurrencyConverter/InrtoDollarRequest", ReplyAction="http://server/CurrencyConverter/InrtoDollarResponse")]
        currency.ServiceReference1.InrtoDollarResponse InrtoDollar(currency.ServiceReference1.InrtoDollarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server/CurrencyConverter/InrtoDollarRequest", ReplyAction="http://server/CurrencyConverter/InrtoDollarResponse")]
        System.Threading.Tasks.Task<currency.ServiceReference1.InrtoDollarResponse> InrtoDollarAsync(currency.ServiceReference1.InrtoDollarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InrtoDollarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InrtoDollar", Namespace="http://server/", Order=0)]
        public currency.ServiceReference1.InrtoDollarRequestBody Body;
        
        public InrtoDollarRequest() {
        }
        
        public InrtoDollarRequest(currency.ServiceReference1.InrtoDollarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InrtoDollarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double a;
        
        public InrtoDollarRequestBody() {
        }
        
        public InrtoDollarRequestBody(double a) {
            this.a = a;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InrtoDollarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InrtoDollarResponse", Namespace="http://server/", Order=0)]
        public currency.ServiceReference1.InrtoDollarResponseBody Body;
        
        public InrtoDollarResponse() {
        }
        
        public InrtoDollarResponse(currency.ServiceReference1.InrtoDollarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InrtoDollarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public InrtoDollarResponseBody() {
        }
        
        public InrtoDollarResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CurrencyConverterChannel : currency.ServiceReference1.CurrencyConverter, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CurrencyConverterClient : System.ServiceModel.ClientBase<currency.ServiceReference1.CurrencyConverter>, currency.ServiceReference1.CurrencyConverter {
        
        public CurrencyConverterClient() {
        }
        
        public CurrencyConverterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CurrencyConverterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencyConverterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencyConverterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        currency.ServiceReference1.InrtoDollarResponse currency.ServiceReference1.CurrencyConverter.InrtoDollar(currency.ServiceReference1.InrtoDollarRequest request) {
            return base.Channel.InrtoDollar(request);
        }
        
        public string InrtoDollar(double a) {
            currency.ServiceReference1.InrtoDollarRequest inValue = new currency.ServiceReference1.InrtoDollarRequest();
            inValue.Body = new currency.ServiceReference1.InrtoDollarRequestBody();
            inValue.Body.a = a;
            currency.ServiceReference1.InrtoDollarResponse retVal = ((currency.ServiceReference1.CurrencyConverter)(this)).InrtoDollar(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<currency.ServiceReference1.InrtoDollarResponse> currency.ServiceReference1.CurrencyConverter.InrtoDollarAsync(currency.ServiceReference1.InrtoDollarRequest request) {
            return base.Channel.InrtoDollarAsync(request);
        }
        
        public System.Threading.Tasks.Task<currency.ServiceReference1.InrtoDollarResponse> InrtoDollarAsync(double a) {
            currency.ServiceReference1.InrtoDollarRequest inValue = new currency.ServiceReference1.InrtoDollarRequest();
            inValue.Body = new currency.ServiceReference1.InrtoDollarRequestBody();
            inValue.Body.a = a;
            return ((currency.ServiceReference1.CurrencyConverter)(this)).InrtoDollarAsync(inValue);
        }
    }
}
